final List<Map<String, dynamic>> hotelList = [
  {
    'image': 'assets/download (1).jpeg',
    'place': 'The Urban Nest',
    'destination': 'London',
    'price': 125,
    'rating': 4.8,
    'distance': '1.2 km from center',
  },
  {
    'image': 'assets/OIP (1).jpeg',
    'place': 'Global Will Suites',
    'destination': 'London',
    'price': 140,
    'rating': 4.6,
    'distance': 'Near Canary Wharf',
  },
  {
    'image': 'assets/download.jpeg',
    'place': 'Skyline Atrium',
    'destination': 'Dubai',
    'price': 168,
    'rating': 4.9,
    'distance': 'Downtown Dubai',
  },
];

final List<Map<String, dynamic>> ticketList = [
  {
    'airline': 'Oceanic Air',
    'from': {
      'code': 'NYC',
      'name': 'New York',
    },
    'to': {
      'code': 'LDN',
      'name': 'London',
    },
    'flying_time': '8H 30M',
    'date': '1 May',
    'departure_time': '08:00 AM',
    'arrival_time': '08:30 PM',
    'number': 23,
    'gate': 'A12',
    'seat': '14A',
    'class': 'Economy Plus',
    'price': 249.99,
    'booking_code': 'B2SG28',
    'e_ticket': '0055 444 77147',
    'passport': '5221 478566',
    'passenger': 'Flutter DB',
    'payment_last4': '2462',
    'terminal': 'T2',
    'status': 'Boarding soon',
  },
  {
    'airline': 'Metro Wings',
    'from': {
      'code': 'DAC',
      'name': 'Dhaka',
    },
    'to': {
      'code': 'SHA',
      'name': 'Shanghai',
    },
    'flying_time': '4H 20M',
    'date': '10 May',
    'departure_time': '09:00 AM',
    'arrival_time': '01:20 PM',
    'number': 45,
    'gate': 'C04',
    'seat': '08C',
    'class': 'Business',
    'price': 399.00,
    'booking_code': 'MW9C45',
    'e_ticket': '7710 240 18452',
    'passport': '4431 905612',
    'passenger': 'Flutter DB',
    'payment_last4': '2462',
    'terminal': 'T1',
    'status': 'Confirmed',
  },
];
